import type { VendorApiScope } from "./apiScopes";

export type IntegrationBranch = { id: string; name: string; active: boolean; status: string; paymentStatus: string | null; isDefault: boolean };
export const scopeLabels: Record<VendorApiScope, string> = {
  "verification:create": "Start student verification", "verification:read": "Read verification results",
  "payments:create": "Create sales", "payments:read": "Read sales and receipts", "payments:cancel": "Cancel unpaid sales", "refunds:create": "Register, recover and execute refunds",
};
export const keyPresets = {
  verification: ["verification:create", "verification:read"],
  payments: ["payments:create", "payments:read", "payments:cancel"],
} as const satisfies Record<string, readonly VendorApiScope[]>;

export type EndpointExample = {
  id: string; group: "verification" | "payments" | "refunds"; title: string; method: "GET" | "POST";
  path: string; scope: VendorApiScope; description: string; fields: string; body?: Record<string, unknown>;
  response: unknown; recovery: string;
};
const payment = { id: "example-request", branchId: "example-branch", vendorName: "Example vendor", branchName: "Example branch", orderReference: "example-sale-001", amountMinor: 3500, currency: "ZAR", status: "PENDING", createdAt: "2026-10-07T10:00:00.000Z", expiresAt: "2026-10-07T10:10:00.000Z", completedAt: null, transactionId: null, qrPayload: "unifywallet://pay-request/example-request", refundedMinor: 0, refundableMinor: 0, refundStatus: "NONE", refunds: [] };
export const pendingRefundExample = { id: "example-operation", vendorProfileId: "example-vendor", operatorId: "api:example-credential", originalTransactionId: "example-spend", paymentRequestId: "example-request", branchId: "example-branch", amountMinor: 1500, currency: "ZAR", idempotencyKey: "example-refund-key-001", status: "PENDING", createdAt: "2026-10-07T10:05:00.000Z", resolvedAt: null };
const completedRefundExample = { ...pendingRefundExample, status: "COMPLETED", resolvedAt: "2026-10-07T10:06:00.000Z", result: { originalTransactionId: "example-spend", refundTransactionId: "example-refund", paymentRequestId: "example-request", refundedAmountMinor: 1500, totalRefundedMinor: 1500, remainingRefundableMinor: 2000, refundStatus: "PARTIALLY_REFUNDED", vendorBalanceMinor: 20000, replayed: false, refund: { id: "example-refund", amountMinor: 1500, currency: "ZAR", source: "API", createdAt: "2026-10-07T10:06:00.000Z" } } };
export const endpoints: EndpointExample[] = [
  { id: "verification-create", group: "verification", title: "Start verification", method: "POST", path: "/verification-sessions", scope: "verification:create", description: "Create or resume the checkout's student verification using the default verification branch.", fields: "checkoutId: your stable checkout reference, 1–128 characters.", body: { checkoutId: "example-checkout-001" }, response: { verificationRequestId: "example-verification", checkoutId: "example-checkout-001", status: "PENDING", isVerified: null, failureCode: null, failureReason: null, student: { id: null, name: null, university: null }, createdAt: "2026-10-07T10:00:00.000Z", expiresAt: "2026-10-07T10:05:00.000Z", completedAt: null, verificationUrl: "https://example.invalid/verify/example-verification" }, recovery: "Reuse the same checkoutId after a lost response. Send the customer to the returned verificationUrl." },
  { id: "verification-read", group: "verification", title: "Read verification", method: "GET", path: "/verification-sessions/{verificationRequestId}", scope: "verification:read", description: "Retrieve the authoritative decision. Approved results can include a safe student summary; raw credential attributes remain inside the portal.", fields: "verificationRequestId: the ID returned when you started verification.", response: { verificationRequestId: "example-verification", checkoutId: "example-checkout-001", status: "APPROVED", isVerified: true, failureCode: null, failureReason: null, student: { id: "EXAMPLE001", name: "Example Student", university: "Example University" }, createdAt: "2026-10-07T10:00:00.000Z", expiresAt: "2026-10-07T10:05:00.000Z", completedAt: "2026-10-07T10:02:00.000Z" }, recovery: "Keep PENDING on screen while awaiting a decision. APPROVED permits your verification-dependent action. DECLINED, EXPIRED and FAILED do not." },
  { id: "payment-create", group: "payments", title: "Create a sale", method: "POST", path: "/payment-requests", scope: "payments:create", description: "Create a fixed amount for the student to review and pay. Credential verification is a separate flow.", fields: "branchId; orderReference and idempotencyKey: stable strings, 1–128 characters; amountMinor: positive safe integer cents; currency: ZAR. 3500 = R35.00.", body: { branchId: "example-branch", orderReference: "example-sale-001", amountMinor: 3500, currency: "ZAR", idempotencyKey: "example-sale-key-001" }, response: payment, recovery: "Save the terms and key before sending. A lost response requires the same instruction and key. A changed instruction needs a new sale reference and key." },
  { id: "payment-list", group: "payments", title: "Find sales", method: "GET", path: "/payment-requests?limit=20&orderReference=example-sale-001", scope: "payments:read", description: "Find your sale by its original order reference.", fields: "limit: 1–50; cursor: optional returned cursor; orderReference: optional exact reference.", response: { items: [payment], nextCursor: null }, recovery: "Search the original reference before creating a replacement sale." },
  { id: "payment-read", group: "payments", title: "Read sale and receipt", method: "GET", path: "/payment-requests/{id}", scope: "payments:read", description: "Read authoritative status, receipt identifiers and completed refund history.", fields: "id: payment request ID. Refund amounts and refunds[] are merchant-only fields.", response: { ...payment, status: "PAID", completedAt: "2026-10-07T10:02:00.000Z", transactionId: "example-spend", refundableMinor: 3500 }, recovery: "Only PAID confirms payment. PENDING, CANCELLED and EXPIRED are not receipts. Continue polling when callbacks are unavailable; read access remains available during payment suspension." },
  { id: "payment-cancel", group: "payments", title: "Cancel an unpaid sale", method: "POST", path: "/payment-requests/{id}/cancel", scope: "payments:cancel", description: "Cancel a pending sale; a competing successful payment remains PAID.", fields: "id: payment request ID. No replacement amount or financial terms.", body: {}, response: { ...payment, status: "CANCELLED" }, recovery: "Inspect the returned state. Repeated cancellation is safe. Read the receipt if payment won the race." },
  { id: "refund-register", group: "refunds", title: "Register a refund", method: "POST", path: "/refund-operations", scope: "refunds:create", description: "Freeze the original sale, refund amount and key. Registration does not move money.", fields: "paymentRequestId: original paid sale; amountMinor: positive safe integer cents; idempotencyKey: stable refund key, 1–128 characters.", body: { paymentRequestId: "example-request", amountMinor: 1500, idempotencyKey: "example-refund-key-001" }, response: pendingRefundExample, recovery: "Persist the instruction before registration. Execute only after an acknowledged registration. Replay identical registration after a lost response; never change its amount or key." },
  { id: "refund-pending", group: "refunds", title: "Find your pending refund", method: "GET", path: "/refund-operations", scope: "refunds:create", description: "Find the current API credential's unresolved operation across clients.", fields: "No financial terms. The API credential identifies the operator.", response: { vendorProfileId: "example-vendor", operatorId: "api:example-credential", operation: pendingRefundExample }, recovery: "One pending operation blocks new instructions for this wallet/operator. Other operators remain independent. Discovery must not automatically execute the refund." },
  { id: "refund-read", group: "refunds", title: "Check a refund", method: "GET", path: "/refund-operations/{id}", scope: "refunds:create", description: "Read the stored instruction and authoritative outcome.", fields: "id: registered operation ID. Outcomes: PENDING, COMPLETED, REJECTED or CANCELLED.", response: pendingRefundExample, recovery: "Keep the original reference after timeout, 401/403, 5xx, missing records or malformed responses. Clear it only after an authoritative terminal outcome. Recovery survives payment suspension; valid identity, scope and branch authorization still apply." },
  { id: "refund-execute", group: "refunds", title: "Execute the registered refund", method: "POST", path: "/refund-operations/{id}/execute", scope: "refunds:create", description: "Post the frozen refund or return its stable outcome. New execution checks current payment eligibility.", fields: "id: operation ID; body: empty object. No replacement terms.", body: {}, response: completedRefundExample, recovery: "A completed operation replays before payment eligibility checks. An unexpected failure remains recoverable as PENDING. Partial refunds have no time limit but their total cannot exceed the original spend." },
  { id: "refund-cancel", group: "refunds", title: "Cancel a pending refund", method: "POST", path: "/refund-operations/{id}/cancel", scope: "refunds:create", description: "Cancel only a pending operation. A competing successful execution returns COMPLETED.", fields: "id: operation ID; body: empty object.", body: {}, response: { ...pendingRefundExample, status: "CANCELLED", resolvedAt: "2026-10-07T10:06:00.000Z" }, recovery: "Use the server outcome. Cancellation cannot undo a completed refund and delayed execution cannot post a cancelled operation." },
  { id: "refund-compatibility", group: "refunds", title: "Compatibility refund endpoint", method: "POST", path: "/payment-requests/{id}/refunds", scope: "refunds:create", description: "Existing integrations can keep this registration/execution wrapper. New integrations should use refund operations.", fields: "id: original payment request; amountMinor; idempotencyKey.", body: { amountMinor: 1500, idempotencyKey: "example-refund-key-001" }, response: { refund: { id: "example-refund", amountMinor: 1500, currency: "ZAR", source: "API", createdAt: "2026-10-07T10:06:00.000Z" }, paymentRequest: { ...payment, status: "PAID", completedAt: "2026-10-07T10:02:00.000Z", transactionId: "example-spend", refundedMinor: 1500, refundableMinor: 2000, refundStatus: "PARTIALLY_REFUNDED", refunds: [{ id: "example-refund", amountMinor: 1500, currency: "ZAR", source: "API", createdAt: "2026-10-07T10:06:00.000Z" }] } }, recovery: "Response example is shortened; the wrapper also includes operation metadata. Retain the original instruction and inspect its operation when the response is lost." },
];

export function exampleRequest(endpoint: EndpointExample, baseUrl: string, branchId: string, language: "curl" | "node") {
  const body = endpoint.body ? { ...endpoint.body, ...(endpoint.id === "payment-create" ? { branchId: branchId || "YOUR_BRANCH_ID" } : {}) } : undefined;
  const url = `${baseUrl.replace(/\/$/, "")}/api/vendor/v1${endpoint.path}`;
  // JSON strings are encoded rather than interpolated into executable shell syntax.
  const shellQuote = (value: string) => `'${value.replace(/'/g, `'"'"'`)}'`;
  if (language === "curl") return `curl --request ${endpoint.method} ${shellQuote(url)} \\\n  --header "Authorization: Bearer $UNIFY_VENDOR_API_KEY"${body ? ` \\\n  --header 'Content-Type: application/json' \\\n  --data ${shellQuote(JSON.stringify(body))}` : ""}`;
  return `// Run on your server. Set UNIFY_VENDOR_API_KEY in its environment.\nconst response = await fetch(${JSON.stringify(url)}, {\n  method: ${JSON.stringify(endpoint.method)},\n  headers: { Authorization: \`Bearer \${process.env.UNIFY_VENDOR_API_KEY}\`${body ? ', "Content-Type": "application/json"' : ""} },${body ? `\n  body: JSON.stringify(${JSON.stringify(body, null, 2)}),` : ""}\n});\nconst result = await response.json();\n// Inspect response.ok and the authoritative result before updating your order.\n// Retain unresolved references on errors; inspect result.status before fulfillment.`;
}

export const troubleshooting = [
  ["401 / invalid API key", "Check the server's bearer key, its revocation status and vendor access. Keep unresolved refund references."],
  ["MISSING_SCOPE", "Create a replacement key with the required permission. Existing keys cannot gain permissions."],
  ["BRANCH_NOT_ALLOWED / REQUEST_NOT_FOUND", "Check vendor ownership, the key's branch list and the original request ID. A missing record does not prove an unknown refund failed."],
  ["VENDOR_PAYMENT_SUSPENDED", "Read existing sales and recover refund operations. New refund execution and new sales require eligibility. Check the vendor wallet and payment status."],
  ["VENDOR_NOT_PAYMENT_ENABLED / BRANCH_NOT_PAYMENT_ENABLED", "Check the payment application and branch acceptance before attempting new financial operations."],
  ["IDEMPOTENCY_CONFLICT / ORDER_REFERENCE_CONFLICT", "Retrieve the original instruction. Reuse its exact terms for recovery; create a new reference only for a genuinely new sale."],
  ["REFUND_OPERATION_PENDING", "Check or cancel this operator's existing operation before registering another refund."],
  ["REFUND_AMOUNT_EXCEEDED / PAYMENT_FULLY_REFUNDED", "Refresh authoritative refund totals. Do not exceed the original spend."],
] as const;

export function signatureExample(kind: "verification" | "payments") {
  return `import { createHmac, timingSafeEqual } from "node:crypto";\n\n// rawBody must be the exact received Buffer, before JSON parsing.\nfunction validSignature(rawBody, signature${kind === "payments" ? ", timestamp" : ""}, secret) {\n  if (!/^sha256=[a-f0-9]{64}$/.test(signature ?? "")) return false;${kind === "payments" ? '\n  if (!/^\\d{10}$/.test(timestamp ?? "")) return false;\n  if (Math.abs(Date.now() / 1000 - Number(timestamp)) > 300) return false;' : ""}\n  const hmac = createHmac("sha256", secret);${kind === "payments" ? '\n  hmac.update(`${timestamp}.`);' : ""}\n  const expected = hmac.update(rawBody).digest();\n  return timingSafeEqual(expected, Buffer.from(signature.slice(7), "hex"));\n}\n\n// Headers: X-Unify-Signature${kind === "payments" ? ", X-Unify-Timestamp" : ""}.\n// Read the corresponding callback secret from your server environment.\n// Verify first, then parse JSON, validate terms and reread authoritative status.\n// Deduplicate X-Unify-Event-Id durably before fulfillment; acknowledge with 2xx.\n// Continue polling if delivery is unavailable.`;
}
