ALTER TYPE "VendorApplicationStatus" ADD VALUE IF NOT EXISTS 'REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_APPLICATION_REVOKED';
ALTER TABLE "vendor_application" ADD COLUMN IF NOT EXISTS "revokedAt" TIMESTAMP(3);
ALTER TABLE "vendor_application" ADD COLUMN IF NOT EXISTS "revokedByUserId" TEXT;
ALTER TABLE "vendor_application" ADD COLUMN IF NOT EXISTS "viewedByAdminAt" TIMESTAMP(3);
