-- Branch-level payment onboarding and campus classification.

CREATE TYPE "CampusStatus" AS ENUM ('ON_CAMPUS', 'OFF_CAMPUS');

ALTER TABLE "vendor_branch"
  ADD COLUMN "campusStatus" "CampusStatus";

ALTER TYPE "BranchPaymentApplicationStatus" ADD VALUE IF NOT EXISTS 'REVOKED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_BRANCH_CAMPUS_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_BRANCH_PAYMENT_APPLICATION_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_BRANCH_PAYMENT_APPLICATION_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_BRANCH_PAYMENT_APPLICATION_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VENDOR_BRANCH_PAYMENT_ACCEPTANCE_CLOSED';
